// <auto-generated />
namespace CRUD.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addneededtables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addneededtables));
        
        string IMigrationMetadata.Id
        {
            get { return "202210272056222_addneededtables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
